### ISSUE TITLE
is required java 8?

### ISSUE THREAD

**Issue by hbro23** [triologygmbh/reCAPTCHA-V2-java#1]
Hello there!

Firstly thanks for this binding, I'm wondering if for the dependencies is necessary to use Java 8, I try to used in Java 7 and I got this error:

`java.lang.UnsupportedClassVersionError: de/triology/recaptchav2java/ReCaptcha : Unsupported major.minor version 52.0`

thanks in advance!

**Comment by schnatterer** [comment]
Hi @hbro23 ,

you still have to use Java 7 😲? It's been EOL for almost 2 and a half years!
 
Yes, reCAPTCHA-V2-java is only compatible with Java 8+, because `Http` [uses a lamdba](https://github.com/triologygmbh/reCAPTCHA-V2-java/blob/master/src/main/java/de/triology/recaptchav2java/Http.java#L45). However, you could change that pretty easily. Just inline `withConnection()`.
Also, you would have to [adapt the source level](https://github.com/triologygmbh/reCAPTCHA-V2-java/blob/master/pom.xml#L55).
HTH

**Comment by hbro23** [comment]
Thanks for info @schnatterer, I will try to change the lambda function!

I know it but it's for a old project.  Thanks again.
Regards
