### ISSUE TITLE
Guava annotation present in artifact

### ISSUE THREAD

**Issue by mrk-autocom** [triologygmbh/reCAPTCHA-V2-java#2]
Hi there
We are evaluating your reCAPTCHA library.
However, the presence of com.google.common.annotations.VisibleForTesting in the artifact causes problems because it differs slightly from the one present in Guava 20, which we are using.
We have a duplicate-finder plugin that complains. Is it possible to remove this class? Can we help?

**Comment by schnatterer** [comment]
I see the following solutions:

1. Remove the annotation (it's for markup only)
1. Introduce guava dependency


Solution 2. is a bit of an overkill because I'd like to have this library to have as few dependencies as possible.
We could use it as optional dependency, though.

But is reCAPTCHA V2 still the latest? Isnt there a V3 now?

**Comment by mrk-autocom** [comment]
I think an optional dependency is a great compromise!
I'll look into v3.

**Comment by mrk-autocom** [comment]
Would you be interested in a pull request?

**Comment by schnatterer** [comment]
On 2nd thought, I came up with a much more lightweight solution: Shade the class.

Please try the current snapshot version as described in the Readme and see if it resolves your problem. If so, close the issue and I'll release a new version.

**Comment by mrk-autocom** [comment]
Sorry, I got caught in another project, and I didn't get time to test it before today.
It works! We appreciate your effort very much.
I think the solution is very pragmatic and to the point.

**Comment by schnatterer** [comment]
Thanks for getting back. I release 1.0.3 containing the new class.
